version: '3.8'

services:
  nucleus-postgres:
    image: postgres:17.5
    container_name: nucleus-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - nucleusdata:/var/lib/postgresql/data
volumes:
  nucleusdata: